### ISSUE TITLE
Curiosity about the httpbeast fork

### ISSUE THREAD

**Issue by dom96** [supranim/supranim#1]
Hey,

I'm just curious why you've decided to fork httpbeast instead of depending on it. Is there something that prevented you from doing so? Would love to fix that if so :)

**Comment by georgelemon** [comment]
Httpbeast is the best! I'm trying to make some experiments inspired by the Laravel-ish flavour, like Aspect Oriented Programming. Technically, there are not too many diferences, yet

**Comment by georgelemon** [comment]
Missing credits, Oups!

**Comment by dom96** [comment]
Can you elaborate? I'm curious what changes you're planning and wondering whether we should make them upstream

**Comment by georgelemon** [comment]
Using httpbeast as a package is the best idea <3
